config/routes.rb
Rails.application.routes.draw do
  root 'page#index'

  get "/login_page", to: "page#login_page"
  get "/login", to: "sessions#new"
  get "logout", to: "sessions#destroy"
  get "/auth/:provider/callback", to: "sessions#create"
  get "/links/:id", to: "links#show"
  get "/links/:id/edit", to: "links#edit"
  post "/links/:id/edit", to:  "links#update"
  get "links/:id/delete", to: "links#delete"

  get "/dashboard", to:   "page#dashboard"
  get "/registration_form", to: "page#registration_form"
  get "/:short_url", to: "links#handle_short_url"
  post "/new/link", to: "links#create_url"
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :statistics

  validates :actual_url, presence: true

  after_create :generate_short_url

  def generate_short_url
    self.short_url = vanity == "" ? id.to_s(36) : vanity
    unless actual_url[0..3] == "http"
      self.actual_url = "http://" + actual_url
    end
    save
  end

  def self.retrieve(id)
    where("user_id = ?", id).order(id: :desc).limit(5)
  end

  def self.popular
    order(visits: :desc).limit(5)
  end

  def self.anonymous
    order(id: :desc).limit(5)
  end
end

app/models/statistic.rb
class Statistic < ActiveRecord::Base
  belongs_to :link

   def self.register(link, request)
    statistic = new
    statistic.ip_address = request.remote_ip
    statistic.referer = request.referer
    statistic.link_id = link.id
    statistic.browser_information = browser_details(request)
    statistic.save
  end

  def self.browser_details(request)
    user_agent = UserAgent.parse(request.env["HTTP_USER_AGENT"])
    "#{user_agent.browser} #{user_agent.version}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :links

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.email = auth.info.email
      user.name = auth.info.name
      user.save
    end
  end

  def self.top
    order(link_count: :desc).limit(5)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def authenticate_user
    @current_user ||= User.find_by(uid: session[:user_id])
    redirect_to root_path unless @current_user
  end
end

app/controllers/concerns/statistic_concern.rb
require "active_support/concern"
module StatisticConcern
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  include ApplicationHelper

before_action :authenticate_user, except: [:create_url, :handle_short_url]

  def create_url
    if vanity_url_exist
      flash[:error] = "Custom URL already exists"
    else
      save_link
    end

    redirect_to dashboard_path
  end

  def handle_short_url
    @link = Link.find_by(short_url: params[:short_url])
    if @link && !@link.deleted
      direct_to_actual_url
    else
      render :deleted_error
    end
  end

  def show
    @link = Link.find_by(id: params[:id])
  end

  def edit
    @link = Link.find_by(id: params[:id])
  end

  def update
    link = Link.find_by(id: params[:id])
    link.update(
      actual_url: params[:actual_url],
      active: active_to_bool(params[:active])
    )
    flash[:update] = "Link Updated Successfully"
    redirect_to dashboard_path
  end

  def delete
    link = Link.find_by(id: params[:id])
    link.update(deleted: true)
    flash[:error] = "Link has been deleted"
    redirect_to dashboard_path
  end

private

  def vanity_url_exist
    vanity = params[:link][:vanity]
    Link.find_by(short_url: vanity) if vanity != ""
  end

  def save_link
    link = Link.create!(link_params)
    link.save
    flash[:short_url] = "#{request.protocol}#{request.host_with_port}"\
    "/#{link.short_url}"
  end

  def link_params
    params.require(:link).permit(:actual_url, :vanity, :user_id)
  end

  def direct_to_actual_url
    if @link.active
      redirect_to @link.actual_url, status: 302
      @link.visits += 1
      Statistic.register(@link, request)
      @link.save
    else
      render :inactive_error
    end
  end

  def active_to_bool(status)
    status == "active" ? true : false
  end

  def inactive_error
  end

  def deleted_error
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  include ApplicationHelper
  before_action :authenticate_user, except: [:index]

  def index
    @popular_links = Link.popular
    @anoymus_links = Link.anonymous
    @top_users = User.top
  end

  def dashboard
    @recent_links = Link.retrieve(@current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
    if User.from_omniauth(env["omniauth.auth"])
      set_session(env["omniauth.auth"])
      redirect_to dashboard_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  def set_session(auth_param)
    session[:user_id] = auth_param[:uid]
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def show_url_message
    if flash[:short_url]
      render partial: "application/url"
    end
  end

  def show_user_message
    if flash[:short_url]
      render partial: "application/user_url_message"
    end
  end

  def login_or_logout
    if @current_user
      link_to "Logout", logout_path, class: "btn btn-primary btn-bavel"
    else
      link_to "Login", login_path, class: "btn btn-primary btn-bavel"
    end
  end

  def user_dashboard
    if @current_user
      link_to "My Dashboard", dashboard_path, class: "btn btn-primary"
    end
  end

  def welcome_user
    if @current_user
      "Hi" + " " + @current_user.name
    end
  end
end

app/helpers/link_helper.rb
module LinkHelper
  def date(created_at)
    created_at.strftime("%b %d %Y")
  end
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/application/_url.html.erb
<div class="url_box" id="url-message">
	<%= link_to(flash[:short_url], flash[:short_url], target: "_blank") %>
</div>

app/views/application/_user_url_message.html.erb
<div class="my-short-url user_url_box">
  <%= link_to(flash[:short_url], flash[:short_url], :target => "_blank") %>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pearlbits</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<%= render 'page/navbar' %>


      <%= yield %>
  <%= render 'page/footer' %>

  </body>
</html>

app/views/links/deleted_error.html.erb
<section class="deletedlink">
<div class="deletedlink"> </div>

</section>

app/views/links/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <h3 class="text-center">Active, Inactive, Delete, Update?</h3>
      <%= form_tag %>
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon3"> <strong> Your Actual Url </strong> </span>
        <%=  text_field_tag  :actual_url,  @link.actual_url , class:"form-control input-lg"   %>
      </div>
      <div class="input-group">
        <span class="input-group-addon" id="basic-addon3"> <strong> render active </strong>or inactive</span>
        <select class="form-control" id="sel1" name="active">
          <% if @link.active %>
          <option value="active" selected>active</option>
          <option value="inactive" >inactive</option>
          <% else %>
          <option value="active">active</option>
          <option value="inactive" selected>inactive</option>
          <% end %>
        </select>
      </div>
      <div class="form-group text-center spacer">
        <%= submit_tag  'Update', class: "btn btn-primary btn-md" %>
        <%=  link_to   'Delete ',  "/links/#{@link.id}/delete", class: "btn btn-primary btn-md" %>
      </div>
    </div>
  </div>
</div>

app/views/links/inactive_error.html.erb
<section class="inactivelink">
<div class="inactivelink"> </div>

</section>

app/views/links/show.html.erb
<div class="spacer"> </div>
<div class="table-responsive">
<table class= "table table bordered">
<tr>
<td> Actual Url</td>
<td> <%=  @link.actual_url %> </td>
</tr>
<tr>
<td> Short Url</td>
<td><%= "#{request.protocol}#{request.host_with_port}/#{@link.short_url}" %></td>
</tr>
<tr>
<td> Created At</td>
<td><%= date(@link.created_at) %></td>
</tr>
<tr>
<td> Visits </td>
<td><%= @link.visits %> </td>
</tr>
</table>
</div>
<div>
<h5 style= "text-align: center"> Further Details about the Link</h5>
<div class="table-responsive">
<table class="table table-bordered">
<thead>
<tr>
<th>Ip Address </th>
<th>Browser_Information</th>
<th>Referer</th>
</thead>
</tr>
<tbody>
 <% @link.statistics.each do |stat|  %>
<tr>
<td><%= stat.ip_address %></td>
<td><%= stat.browser_information %></td>
<td><%=  stat.referer %></td>
</tr>
<% end %>
</tbody>
</table>
</table>
</div>
<div class="spacer"></div>

app/views/page/_footer.html.erb
<footer>
    <div class="container">
            <div>
                2016 &copy; Copyright PearlBits <br> All rights Reserved.
            </div>
</footer>

app/views/page/_navbar.html.erb
<nav class="navbar navbar-fixed-top ">
  <div class='navbar-pearl container'>
    <a href="/">
      <%= image_tag("pearl_bits_logo.png") %>
    </a>

    <ul class='navbar-nav nav pull-right'>

      <li class="butomn">
         <%= welcome_user %>
         </li>
         <li>
        <%= user_dashboard %>
      </li>
      <li>
        <%= login_or_logout %>
      </li>
    </ul>

    </div>
</nav>

<!--

	<nav class="navbar navbar-fixed-top">
		<div class="container relative">
			<div class="navbar-header">

			</div>
			<div id="navbar" class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<%= link_to "", root_path, class:"navbar-brand" %>

				</ul>
                <ul class="navbar-right">
                <li>                <span class="welcome"><%= welcome_user %></span></li>
                <li>

                <%= user_dashboard %>
                <%= login_or_logout %>
                </li>
				</ul>
			</div>
		</div>
	</nav>

 -->

app/views/page/_pearlbits_cards.html.erb
<section id="Features">
  <div class="container">
    <div class="row">
      <div class="col-md-4">
        <div class="pricing-table primary">
          <div class="pricing-title">
            <h5>Popular Links</h5>

          </div>
          <div class="pricing-list">
            <ul>
              <% @popular_links.each do |link| %>
              <li><%= link_to "#{request.protocol}#{request.host_with_port}/#{link['short_url']}", "/#{link.short_url}", target: "_blank" %> &nbsp; &nbsp;<br> <span class="badge"> <%= pluralize(link.visits, "hit") %> </span></li> </li></br>
              <% end %>


            </ul>
          </div>
          <div class="pricing-footer">
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="pricing-table primary">
          <div class="pricing-title color-box-second">
            <h5>Recent Links</h5>
          </div>
          <div class="pricing-list ">
            <ul>
              <% @anoymus_links.each do |link| %>
              <li><%= link_to  "#{request.protocol}#{request.host_with_port}/#{link['short_url']}", "/#{link.short_url}", :target => "_blank" %> &nbsp; &nbsp; <br> <span class="badge"> <%= pluralize(link.visits, "hit") %> </span></li></br>

              <% end %>


            </ul>

          </div>
          <div class="pricing-footer">
          </div>
        </div>
      </div>
      <div class="col-md-4">
        <div class="pricing-table secondary">
          <div class="pricing-title color-box-third">
            <h5>Top PearlBiters</h5>
          </div>
          <div class="pricing-list">
            <ul>
              <% @top_users.each do |user| %>
              <li><%= user.name %> </li>
              <% end %>
            </ul>
          </div>
          <div class="pricing-footer">
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/page/_users_card.html.erb
<div class="container">
  <div class="col-md-4">
    <div class="pricing-table primary">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <div class="row">
            <div class="col-xs-3">
              <i class="glyphicon glyphicon-user"></i>
            </div>
            <div class="col-xs-9 text-center"><h3>My Recent Links</h3></div>
          </div>
        </div>
      </div>
      <div class="pricing-list">
        <ul>
          <% @recent_links.each do |link| %>
          <li><%= link_to  "#{request.protocol}#{request.host_with_port}/#{link['short_url']}", "/#{link.short_url}", :target => "_blank" %>  <br>  <%= link_to 'Details', "links/#{link.id}", class: "custombutton" %>
            <%= link_to 'edit', "links/#{link.id}/edit", class: "custombutton" %></br></li>
            <% end %>

          </ul>

        </div>
        <div class="pricing-footer">
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="pricing-table primary">
        <div class="panel panel-green">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <i class="glyphicon glyphicon-th-large"></i>
              </div>
              <div><h3> My Actual Url</h3></div>
            </div>
          </div>
        </div>
        <div class="pricing-list">
          <ul>
            <% @recent_links.each do |link| %>
            <li><%= link_to  link.actual_url, link.actual_url  %>  </li>
            <% end %>
          </ul>
        </div>
        <div class="pricing-footer">
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="pricing-table primary">
        <div class="panel panel-yellow">
          <div class="panel-heading">
            <div class="row">
              <div class="col-xs-3">
                <span class=" glyphicon glyphicon-hand-up"></span>
              </div>
              <div><h3>Total Visits Counts</h3></div>
            </div>
          </div>
        </div>
        <div class="pricing-list">
          <ul>
            <% @recent_links.each do |link| %>
            <li><b><span class="badge"><%= pluralize(link.visits, "hit") %></br></span> </li>
              <% end %>
            </ul>
          </div>
          <div class="pricing-footer">
          </div>
        </div>
      </div>
    </div>

app/views/page/dashboard.html.erb
<div class="container my-c">
  <div class="row">
    <div class="col-lg-8 col-lg-offset-2">
      <div class="spacer">
        <div class="spacer"> </div>
      </div>
      <h3> <%= flash[:update] %></h3>
      <h3> <%= flash[:error] %></h3>
      <%= form_for(:link, url: new_link_path, :html => {class: 'form-horizontal'}) do |f| %>
      <div class="spacer"> </div>
      <div class="container">
        <div class="form-group">
          <div class="input-group">
            <%= f.text_field :actual_url,  pattern: "(https?:\/\/)?([a-Z0-9\-]+\.[a-Z]{2,3})", class: "validate", placeholder: "e.g bitly.com" ,class:"my-input", required: true, data: { success: "ok", error: "Invalid" }  %>
          </div>
          <div class="input-group">
            <%= f.text_field :vanity, placeholder: "optional" ,class:"my-input"   %>
            <%= f.hidden_field :user_id, value: @current_user.id, class:"my-input"   %>
          </div>
          <div class="my-button">
            <%= f.submit 'Shorten Url' ,class: "btn btn-primary btn-md" %>
            <% end %>
          </div>

          <%= show_user_message %>
        </div>
      </div>
    </div>
  </div>
</div>
<div class="spacer"></div>
<%= render partial:  'users_card' %>

app/views/page/index.html.erb
<section class="firstintro bg-testimonial">
  <div class="overlay"></div>
  <div class="container"></div>
  <div class="title-section small">
    <h4>Join PearlBits</h4>
    <p>leading link shortener built with rails....</p>
  </div>
  <div class="container">
    <div class="col-lg-8 col-lg-offset-2">
      <%= form_for(:link, url: new_link_path) do |f| %>
      <div class="input-group">
        <%= f.text_field :actual_url,  pattern: "(https?:\/\/)?([a-Z0-9\-]+\.[a-Z]{2,3})", class: "validate", placeholder: "e.g bitly.com" ,class:"form-control", required: true, data: { success: "ok", error: "Invalid" }  %>
        <span class="input-group-btn">
          <%= f.hidden_field :vanity, value: "", placeholder: "e.g bitly.com" ,class:"form-control input-lg" %>
          <% if @current_user %> <%= f.hidden_field :user_id, value: @current_user.id, class:"my-input"   %> <% end %>
          <%= f.submit 'PearlBit!' ,class: "btn btn-primary btn-md", id: "make-link"%>
        </span>
      </div>
    </div>
  </div>
  <%= show_url_message %>
  <% end %>
</section>
<%= render partial: 'pearlbits_cards' %>